# 101 Pandas Exercises for Data Analysis
My solutions for [101 Pandas Exercises for Data Analysis](https://machinelearningplus.com/python/101-pandas-exercises-python-interactive/).

I started this project to practice and improve my pandas skills for data analysis.

In [1]:
# 1.How to import pandas and check the version?
import pandas as pd
import numpy as np

In [13]:
pd.__version__

'3.0.5'

In [46]:
# 2.How to create a series from a list, numpy array and dict
# Create a pandas series from each of the items below: a list, numpy and a dictionary
mylist = list("abcdefghijklmnopqrstuvwxyz")
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [47]:
s1 = pd.Series(mylist)
pdlist.head()

0    a
1    b
2    c
3    d
4    e
dtype: str

In [48]:
s2 = pd.Series(myarr)
s2.tail()

21    21
22    22
23    23
24    24
25    25
dtype: int64

In [49]:
s3 = pd.Series(mydict)
s3.head(10)

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
i    8
j    9
dtype: int64

In [50]:
# 3.How to convert the index of a series into a column of a dataframe?
# Convert the series ser into a dataframe with its index as another column on the dataframe
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
ser.head()

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [51]:
df = ser.to_frame().reset_index()
df.head()

  index  0
0     a  0
1     b  1
2     c  2
3     d  3
4     e  4

In [52]:
# 4.How to combine many series to form a dataframe?
# Combine ser1 and ser2 to form a dataframe
ser1 = pd.Series(list("abcedfghijklmnopqrstuvwxyz"))
ser2 = pd.Series(np.arange(26))

In [53]:
df = pd.concat([ser1, ser2], axis=1)
df.columns =["col1", "col2"]
df.head()

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [54]:
# 4.the other Solutions
df2= pd.DataFrame({"col1": ser1, "col2": ser2})
df2.head()

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [55]:
# 5.How to assign name to the series' index?
# Give a name to the series ser calling it 'alphabets'
ser = pd.Series(list("abcedfghijklmnopqrstuvwxyz"))

In [56]:
ser.name = "alpahebets"
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alpahebets, dtype: str

In [5]:
# 6.How to get the items of series A not present in series B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [6]:
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [7]:
# 7.How to get the items not common to both series A and series B?
set(ser1)

{1, 2, 3, 4, 5}

In [8]:
set(ser2)

{4, 5, 6, 7, 8}

In [9]:
set(ser1) ^ set(ser2)

{1, 2, 3, 6, 7, 8}

In [15]:
x = list(set(ser1) ^ set(ser2))
type(x)

list

In [16]:
pd.Series(x)

0    1
1    2
2    3
3    6
4    7
5    8
dtype: int64

In [22]:
# 7.Solution
ser_u = pd.Series(np.union1d(ser1, ser2)) # union
ser_i = pd.Series(np.intersect1d(ser1, ser2)) # intersect
ser_u[~ser_u.isin(ser_i)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [27]:
# 8.How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?
ser = pd.Series(np.random.normal(10, 5, 25))
ser.head()

0    -0.060540
1    10.280742
2    18.282375
3     7.323646
4    10.865861
dtype: float64

In [33]:
np.percentile(ser, q=[0, 25, 50, 75, 100])

array([-0.06053994,  8.26876179, 10.02813902, 13.75046196, 19.17387561])

In [35]:
# 9.How to get frequency counts of unique items of a series?
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.head()

0    h
1    g
2    g
3    f
4    b
dtype: str

In [36]:
ser.value_counts()

b    9
f    5
d    5
g    3
e    3
c    2
a    2
h    1
Name: count, dtype: int64

In [38]:
# 10.How to keep only top 2 most frequent values as it is and replace everything else as "Other"?
np.random.seed(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
ser.head()

0    1
1    1
2    4
3    4
4    4
dtype: int64

In [108]:
type(ser)

pandas.Series

In [118]:
ser = ser.astype('object')
ser.dtype

dtype('O')

In [119]:
top_two = ser.value_counts().index[:2]
top_two

Index([1, 4], dtype='object')

In [120]:
ser[~ser.isin(top_two)] = "Other"
ser

0         1
1         1
2         4
3         4
4         4
5         4
6         1
7     Other
8     Other
9         1
10    Other
11    Other
dtype: object

In [3]:
# 11.How to bin a numeric series to 10 groups of equal size?
ser = pd.Series(np.random.random(20))
ser.head()

0    0.163181
1    0.808899
2    0.764560
3    0.476927
4    0.439844
dtype: float64

In [6]:
binned_data = pd.qcut(ser, q=10, labels=["1st","2nd","3rd","4th","5th","6th","7th","8th","9th","10th"])
binned_data

0      1st
1      8th
2      8th
3      4th
4      3rd
5      2nd
6      3rd
7      7th
8      6th
9      9th
10    10th
11     6th
12     5th
13     4th
14     9th
15     7th
16     5th
17    10th
18     2nd
19     1st
dtype: category
Categories (10, str): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

In [10]:
# 12.How to convert a numpy array to a dataframe of given shape?
# Reshape the series ser into a dataframe with 7 rows and 5 columns
ser = pd.Series(np.random.randint(1, 10, 35))
ser.head()

0    9
1    9
2    7
3    1
4    3
dtype: int64

In [15]:
pd.DataFrame(ser.values.reshape(7,5))

   0  1  2  3  4
0  9  9  7  1  3
1  3  5  4  3  1
2  3  9  7  1  9
3  4  1  5  2  2
4  4  9  4  9  3
5  9  2  6  5  7
6  2  1  9  3  1

In [16]:
# 13.How to find the positions of numbers that are multiples of 3 from a series?
# Find the positions of numbers that are multiples of 3 from ser
ser = pd.Series(np.random.randint(1, 10, 7))
ser

0    7
1    5
2    9
3    9
4    1
5    7
6    4
dtype: int64

In [32]:
ser[ser % 3 == 0].index.tolist()

[2, 3]

In [33]:
# 13.Solution
np.argwhere(ser % 3 ==0)

array([[2],
       [3]])

In [34]:
# 14.How to extract items at given positions from a series
# From ser, extract the items at positions in list pos
ser = pd.Series(list("abcdefghijklmnopqrstuvwxyz"))
pos = [0, 4, 8, 14, 20]

In [36]:
ser.iloc[pos]

0     a
4     e
8     i
14    o
20    u
dtype: str

In [37]:
# 14.Solution
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: str

In [39]:
# 15.How to stack two series vertically and horizontally?
# Stack ser1 and ser2 vetically and horizontally (to form a dataframe)
ser1 = pd.Series(range(5))
ser2 = pd.Series(list("abcde"))
print(ser1)
print(ser2)

0    0
1    1
2    2
3    3
4    4
dtype: int64
0    a
1    b
2    c
3    d
4    e
dtype: str

In [41]:
pd.DataFrame((ser1,ser2)).T

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [42]:
pd.concat([ser1,ser2], axis=1)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [2]:
# 16.How to get the positions of items of series A in another series B?
# Get the positions of items of ser2 in ser1 as a list.
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

In [13]:
ls = pd.Index(ser1).get_indexer(ser2)
ls.tolist()

[5, 4, 0, 8]

In [27]:
# 16.Solution 1
[np.where(i == ser1)[0].tolist()[0] for i in ser2]

[5, 4, 0, 8]

In [28]:
# 16.Solution 2
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

In [35]:
# 17.How to compute the mean squared error on a truth and predicted series?
# Complete the mean squared error of truth an pred series.
np.random.seed(1)
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
pred

0    0.417022
1    1.720324
2    2.000114
3    3.302333
4    4.146756
5    5.092339
6    6.186260
7    7.345561
8    8.396767
9    9.538817
dtype: float64

In [43]:
((truth - pred) ** 2).mean()

np.float64(0.14160964172544444)

In [44]:
# 17.Solution
np.mean((truth - pred) ** 2)

np.float64(0.14160964172544444)

In [45]:
# 18.How to convert the first character of each element in a series to uppercase?
# Change the first character of each word to upper case in each word of ser.
ser = pd.Series(["how", "to", "kick", "ass?"])
ser

0     how
1      to
2    kick
3    ass?
dtype: str

In [49]:
ser.str.title()

0     How
1      To
2    Kick
3    Ass?
dtype: str

In [50]:
# 18.Solution 1
ser.map(lambda x: x.title())

0     How
1      To
2    Kick
3    Ass?
dtype: str

In [51]:
# 18.Solution 2
ser.map(lambda x: x[0].upper() + x[1:])

0     How
1      To
2    Kick
3    Ass?
dtype: str

In [52]:
# 19.How to calculate the number of characters in each word in series?
ser = pd.Series(["how", "to", "kick", "ass?"])

In [62]:
ser.str.len()

0    3
1    2
2    4
3    4
dtype: int64

In [63]:
# 19.Solution
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    4
dtype: int64

In [65]:
# 20.How to compute difference of differences between consecutive numbers of series?
# Difference of differences between the consecutive numbers of ser.
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [78]:
ser.shift(-1) - ser

0    2.0
1    3.0
2    4.0
3    5.0
4    6.0
5    6.0
6    8.0
7    NaN
dtype: float64

In [93]:
diff= ser.diff().tolist()
diff

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]

In [95]:
np.diff(diff).tolist()

[nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

In [2]:
# 21.How to convert a series of date-string to a timeseries?
ser= pd.Series(["01 Jan 2010", "02-02-2011", "20120303", "2013/04/04", "2014-05-05", "2015-06-06T12:20"])
ser

0         01 Jan 2010
1          02-02-2011
2            20120303
3          2013/04/04
4          2014-05-05
5    2015-06-06T12:20
dtype: str

In [16]:
pd.to_datetime(ser, format="mixed", errors="coerce")

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[us]

In [17]:
# 21.Solution
from dateutil.parser import parse
ser.map(lambda x: parse(x))

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[us]

In [20]:
# 22.How to get the day of month, week number, day of year and day of week from a series of date strings?
# Get the day of month, week number, day of year and day of week from ser.
ser = pd.Series(["01 Jan 2010", "02-02-2011", "20120303", "2013/04/04", "2014-05-05", "2015-06-06T12:20"])

In [21]:
dates = pd.to_datetime(ser, format="mixed", errors="coerce")

In [22]:
day_of_month = dates.dt.day
day_of_month

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32

In [23]:
week_number = dates.dt.isocalendar().week
week_number

0    53
1     5
2     9
3    14
4    19
5    23
Name: week, dtype: UInt32

In [24]:
day_of_year = dates.dt.dayofyear
day_of_year

0      1
1     33
2     63
3     94
4    125
5    157
dtype: int32

In [26]:
day_of_week = dates.dt.day_name()
day_of_week

0       Friday
1    Wednesday
2     Saturday
3     Thursday
4       Monday
5     Saturday
dtype: str

In [27]:
# 23.How to convert year-month string to dates corresponding to the 4th day of the month?
# Change ser to dates that start with 4th of the respective months.
ser = pd.Series(["Jan 2010", "Feb 2011", "Mar 2012"])

In [30]:
dates = pd.to_datetime(ser, format="mixed", errors="coerce")
dates

0   2010-01-01
1   2011-02-01
2   2012-03-01
dtype: datetime64[us]

In [41]:
dates.dt.to_period("M").dt.to_timestamp() + pd.Timedelta(days=3)

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[us]

In [42]:
# 23.Solution
from dateutil.parser import parse
ser.map(lambda x: parse("04" + x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[us]

In [44]:
# 24.How to filter words that contain atleast 2 vowels from a series?
# From ser, extract words that contain atleast 2 vowels.
ser = pd.Series(["Apple", "Orange", "Plan", "Python", "Money"])

In [57]:
vowels = "[aeiou]"
v_counts = ser.str.count(vowels, flags=2)
ser[v_counts >= 2]

0     Apple
1    Orange
4     Money
dtype: str

In [59]:
# 24.Solution
from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i,0) for i in list("aeiou")]) >= 2)
ser[mask]

0     Apple
1    Orange
4     Money
dtype: str

In [5]:
# 25.How to filter valid emails form a series?
# Extract the valid emails from the series emails. The regex pattern for valid emails is provided as reference.
emails = pd.Series(["buying books at amazom.com", "rameses@egypt.com", "matt@t.co", "narendra@modi.com"])
pattern = "[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}"
emails

0    buying books at amazom.com
1             rameses@egypt.com
2                     matt@t.co
3             narendra@modi.com
dtype: str

In [19]:
email_pattern = r"([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})"

In [22]:
list(emails.str.extract(email_pattern, expand=False))

[nan, 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

In [25]:
# 25.Solution
import re
emails.str.findall(pattern, flags=re.IGNORECASE)

0                     []
1    [rameses@egypt.com]
2            [matt@t.co]
3    [narendra@modi.com]
dtype: object

In [27]:
# 26.How to get the mean of a series grouped by another series?
# Compute the mean of weights of each fruit.
fruit = pd.Series(np.random.choice(["apple", "banana", "carrot"], 10))
weight = pd.Series(np.linspace(1, 10, 10))
fruit.tolist()

['banana',
 'carrot',
 'apple',
 'banana',
 'carrot',
 'banana',
 'banana',
 'banana',
 'carrot',
 'banana']

In [28]:
weight.tolist()

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

In [35]:
pd.DataFrame({"fruit": fruit, "weight": weight}).groupby("fruit")["weight"].mean()

fruit
apple     3.000000
banana    6.000000
carrot    5.333333
Name: weight, dtype: float64

In [36]:
# 26.Solution
weight.groupby(fruit).mean()

apple     3.000000
banana    6.000000
carrot    5.333333
dtype: float64

In [47]:
# 27.How to compute the euclidean distance between two series?
# Compute the euclidean distance between series(points) p and q, without using a package formula.
p = pd.Series(np.arange(1, 11))
q = pd.Series(np.arange(10, 0, -1))

In [63]:
(p - q) ** 2

0    81
1    49
2    25
3     9
4     1
5     1
6     9
7    25
8    49
9    81
dtype: int64

In [67]:
((p - q) ** 2).sum()

np.int64(330)

In [71]:
((p - q) ** 2).sum() ** 0.5

np.float64(18.16590212458495)

In [73]:
# 27.Solution
np.linalg.norm(p-q)

np.float64(18.16590212458495)

In [2]:
# 28.How to find all the local maxima(or peaks) in a numeric series?
# Get the positions of peaks (values surrounded by smaller values on both sides) in ser.
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

In [17]:
ser.shift(1)

0     NaN
1     2.0
2    10.0
3     3.0
4     4.0
5     9.0
6    10.0
7     2.0
8     7.0
dtype: float64

In [18]:
ser.shift(-1)

0    10.0
1     3.0
2     4.0
3     9.0
4    10.0
5     2.0
6     7.0
7     3.0
8     NaN
dtype: float64

In [20]:
(ser > ser.shift(1)) & (ser > ser.shift(-1))

0    False
1     True
2    False
3    False
4    False
5     True
6    False
7     True
8    False
dtype: bool

In [21]:
peaks = (ser > ser.shift(1)) & (ser > ser.shift(-1))
ser[peaks].index

Index([1, 5, 7], dtype='int64')

In [23]:
# 28.Solution
dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] + 1
peak_locs

array([1, 5, 7])

In [24]:
# 29.How to replace missing spaces in a string with the least frequent character?
# Replace the spaces in my_str with the least frequent character.
my_str = "dbc deb abed gade"

In [42]:
ser = pd.Series(list(my_str))
freq = ser.value_counts(ascending=True)
freq

c    1
g    1
a    2
b    3
     3
e    3
d    4
Name: count, dtype: int64

In [49]:
least_freq_char = freq.index[0]
least_freq

'g'

In [53]:
my_str.replace(" ", least_freq_char)

'dbccdebcabedcgade'

In [55]:
# 29.Solution
freq = ser.value_counts()
least_freq = freq.dropna().index[-1]
"".join(ser.replace(' ', least_freq))

'dbcgdebgabedggade'

In [56]:
# 30.How to create a TimeSeries starting "2000-01-01" and 10 weekends(Saturdays) after that having random numbers as values?

In [58]:
# How to create a TimeSeries with 10 Saturdays starting from 2000-01-01, filled with random numbers?
start_time = "2000-01-01"
dates = pd.date_range(start_time, periods=10, freq="W-SAT")
dates

DatetimeIndex(['2000-01-01', '2000-01-08', '2000-01-15', '2000-01-22',
               '2000-01-29', '2000-02-05', '2000-02-12', '2000-02-19',
               '2000-02-26', '2000-03-04'],
              dtype='datetime64[us]', freq='W-SAT')

In [65]:
random_values = np.random.randint(1,10,10)

In [71]:
pd.Series(random_values, index=dates)

2000-01-01    8
2000-01-08    3
2000-01-15    2
2000-01-22    1
2000-01-29    5
2000-02-05    3
2000-02-12    5
2000-02-19    6
2000-02-26    5
2000-03-04    2
Freq: W-SAT, dtype: int64

In [58]:
# 31.How to fill an intermittent time series so all missing dates show up with values of previous non-missing data?
# ser has missing dates and values. Make all missing dates appear and fill up with value from previous date.
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(["2000-01-01", "2000-01-03", "2000-01-06", "2000-01-08"]))
ser

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64

In [64]:
new_index = pd.date_range(start=ser.index.min(), end=ser.index.max())

In [68]:
ser.reindex(new_index).ffill()

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

In [69]:
# 31.Solution
ser.resample("D").ffill()

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

In [106]:
# 32.How to compute the autocorrelations of a numeric series?
# Compute autocorrelations for the first 10 lags of ser. Find out which lag has the largest correlation.
np.random.seed(2)
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
ser.head()

0    -3.167578
1     1.437332
2   -18.361961
3    20.402708
4   -12.934356
dtype: float64

In [187]:
autocorr_list = [ser.autocorr(lag=lag) for lag in range(1, 11)]
autocorr_list

[np.float64(0.160301091338246),
 np.float64(0.2577090998974438),
 np.float64(0.358107652646109),
 np.float64(0.09798943758461248),
 np.float64(0.4480559065150124),
 np.float64(0.2815883965092916),
 np.float64(0.10065470560990152),
 np.float64(0.3847166849051962),
 np.float64(-0.18865747775893824),
 np.float64(-0.28441368044305765)]

In [188]:
autocorr_series = pd.Series(autocorr_list, index=range(1, 11))
autocorr_series

1     0.160301
2     0.257709
3     0.358108
4     0.097989
5     0.448056
6     0.281588
7     0.100655
8     0.384717
9    -0.188657
10   -0.284414
dtype: float64

In [190]:
largest_lag = autocorr_series.abs().idxmax()
largest_lag
# abs() 数字のプラス・マイナスを取り除いて、絶対値にする
# idxmax() 一番大きい値を持つ要素のインデックスを取得する

5

In [193]:
# 32.Solution
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
autocorrelations[1:]
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)

Lag having highest correlation:  5

In [13]:
# 33.How to import only every nth row from a csv file to create a dataframe?
# Import every 50th row of BostonHousing dataset as a dataframe.
df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv")
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [14]:
df.iloc[::50].head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
50,0.08873,21.0,5.64,0,0.439,5.963,45.7,6.8147,4,243,16.8,395.56,13.45,19.7
100,0.14866,0.0,8.56,0,0.520,6.727,79.9,2.7778,5,384,20.9,394.76,9.42,27.5
150,1.65660,0.0,19.58,0,0.871,6.122,97.3,1.6180,5,403,14.7,372.80,14.10,21.5
200,0.01778,95.0,1.47,0,0.403,7.135,13.9,7.6534,3,402,17.0,384.30,4.45,32.9

In [17]:
# 33.Solution
df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv", chunksize=50)
df2 = pd.concat([chunk.iloc[0] for chunk in df], axis=1).T
df2.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
50,0.08873,21.0,5.64,0.0,0.439,5.963,45.7,6.8147,4.0,243.0,16.8,395.56,13.45,19.7
100,0.14866,0.0,8.56,0.0,0.520,6.727,79.9,2.7778,5.0,384.0,20.9,394.76,9.42,27.5
150,1.65660,0.0,19.58,0.0,0.871,6.122,97.3,1.6180,5.0,403.0,14.7,372.80,14.10,21.5
200,0.01778,95.0,1.47,0.0,0.403,7.135,13.9,7.6534,3.0,402.0,17.0,384.30,4.45,32.9

In [57]:
# 34.How to change column values when importing csv to a dataframe?
# Import the boston housing dataset, but while importing change the "medv"(median house value) column so that values 25 becomes "Hight".
data = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv")

In [60]:
new_medv = pd.Series(np.where(data["medv"] >= 25, "High", "Low"))
new_medv

0       Low
1       Low
2      High
3      High
4      High
       ...
501     Low
502     Low
503     Low
504     Low
505     Low
Length: 506, dtype: str

In [64]:
fixed_data = data.copy()
fixed_data["medv"] = new_medv
fixed_data.head(10)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,Low
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,Low
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,High
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,High
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,High
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,High
6,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.43,Low
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311,15.2,396.90,19.15,High
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311,15.2,386.63,29.93,Low
9,0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311,15.2,386.71,17.10,Low

In [66]:
# 34.Solution
df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv", 
converters={"medv": lambda x: "High" if float(x) > 25 else "Low"})
df.head(10)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,Low
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,Low
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,High
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,High
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,High
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,High
6,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.43,Low
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311,15.2,396.90,19.15,High
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311,15.2,386.63,29.93,Low
9,0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311,15.2,386.71,17.10,Low

In [68]:
# 35.How to create a dataframe with rows as strides from a given series?
L = pd.Series(range(15))

In [125]:
window_size = 5
step_size = 2

In [124]:
range(0, len(L) - window_size + 1, step_size)

range(0, 11, 2)

In [126]:
stride_list = [
    L.iloc[i: i + window_size].values
    for i in range(0, len(L) - window_size +1, step_size)
]
stride_list

[array([0, 1, 2, 3, 4]),
 array([2, 3, 4, 5, 6]),
 array([4, 5, 6, 7, 8]),
 array([ 6,  7,  8,  9, 10]),
 array([ 8,  9, 10, 11, 12]),
 array([10, 11, 12, 13, 14])]

In [127]:
pd.DataFrame(stride_list)

    0   1   2   3   4
0   0   1   2   3   4
1   2   3   4   5   6
2   4   5   6   7   8
3   6   7   8   9  10
4   8   9  10  11  12
5  10  11  12  13  14

In [128]:
# 35.Solution
def gen_strides(a, stride_len=5, window_len=5):
 n_strides = ((a.size-window_len)//stride_len) + 1
 return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])